<?php
return array(
    'db_connection' => 'mysql',
    'db_bkup_type' => 'gzip',
    'db_bkup_dateFormat' => 'Y-m-d-H-i-s',
    'expectationId' => '3',
    'color' => 'MediumOrchid',
    'colors' => 'red',
    'veryLowrating' => '#FF0000',
    'lowRating' => '#FF69B4 ',
    'achievedRating' => '#FFFAFA',
    'exceedRating' => '#90EE90 ',
    'farExceedrating' => '#32CD32',
    'projectManagerId' => '3',
    'projectLeadId' => '2',
    'adminId' => '5',
    'projectManagerLead' => '6',
    'allUserId' => '0',
    'peopleId' => '4',
    'allUserName' => 'All',
    'status' => '1',
    'type' => '2',
    'list-of-users' => 'userSlug',
    'list-projects' => 'projectSlug',
    'practiceLeadId' => '2',
    'projectManagersId' => '3',
    'practice_head_designation_id' => 20,
    'PMOId' => 'CE406',
    'adminLogin' => 'admin@npat.com',
    'adminPassword' => 'admin123',
    'pmLogin' => 'shan@npat.com',
    'pmPassword' => 'shan@123',
    'plLogin' => 'vijay@npat.com',
    'plPassword' => 'vijay@123',
    'DeliveryHead' => '1',
    'DirectorofDelivery' => '58',
    'metric_percentage1' => [1 => 80, 2 => 0, 3 => 20],
    'metric_percentage2' => [1 => 75, 2 => 5, 3 => 20],
    'metric_percentage3' => [1 => 70, 2 => 10, 3 => 20],
    'metric_percentage4' => [0 => 100],
    'metric_percentage5' => [1 => 0, 2 => 0, 3 => 0],
    'designation_group1' => [5,6],
    'designation_group2' => [42,46,48,49,50],
    'designation_group3' => [39,40,51,52,23,31,45,47,44,3,7,29,16,17],
    'designation_group4' => [20,22,4,38],
    'months' => [1 => 'Jan-Mar',
                 2 => 'Apr-Jun', 
                 3 => 'Jul-Sep',
                 4 => 'Oct-Dec']
);
?>