<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('permissions')->delete();

        \DB::table('permissions')->insert(array(
            0 =>
                array(
                    'id' => 2,
                    'name' => 'List Projects',
                    'slug' => 'list-projects',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 1,
                    'permission_basic_type_id' => 2,
                ),
            1 =>
                array(
                    'id' => 3,
                    'name' => 'Add Projects',
                    'slug' => 'add-projects',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 1,
                    'permission_basic_type_id' => 1,
                ),
            2 =>
                array(
                    'id' => 4,
                    'name' => 'Edit Projects',
                    'slug' => 'edit-projects',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 1,
                    'permission_basic_type_id' => 3,
                ),
            3 =>
                array(
                    'id' => 5,
                    'name' => 'Delete Projects',
                    'slug' => 'delete-projects',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 1,
                    'permission_basic_type_id' => 4,
                ),
            4 =>
                array(
                    'id' => 6,
                    'name' => 'List of Navigators',
                    'slug' => 'list-of-navigators',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 2,
                    'permission_basic_type_id' => 2,
                ),
            5 =>
                array(
                    'id' => 7,
                    'name' => 'Assign Navigators',
                    'slug' => 'assign-navigators',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 2,
                    'permission_basic_type_id' => 1,
                ),
            6 =>
                array(
                    'id' => 8,
                    'name' => 'Edit Navigators',
                    'slug' => 'edit-navigators',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 2,
                    'permission_basic_type_id' => 3,
                ),
            7 =>
                array(
                    'id' => 9,
                    'name' => 'Delete Navigators',
                    'slug' => 'delete-navigators',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 2,
                    'permission_basic_type_id' => 4,
                ),
            8 =>
                array(
                    'id' => 10,
                    'name' => 'List of Users',
                    'slug' => 'list-of-users',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 3,
                    'permission_basic_type_id' => 2,
                ),
            9 =>
                array(
                    'id' => 11,
                    'name' => 'Add Users',
                    'slug' => 'add-users',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 3,
                    'permission_basic_type_id' => 1,
                ),
            10 =>
                array(
                    'id' => 12,
                    'name' => 'Edit Users',
                    'slug' => 'edit-users',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 3,
                    'permission_basic_type_id' => 3,
                ),
            11 =>
                array(
                    'id' => 13,
                    'name' => 'Delete Users',
                    'slug' => 'delete-users',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 3,
                    'permission_basic_type_id' => 4,
                ),
            12 =>
                array(
                    'id' => 14,
                    'name' => 'List of Metrics',
                    'slug' => 'list-of-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 2,
                ),
            13 =>
                array(
                    'id' => 15,
                    'name' => 'Add Metrics',
                    'slug' => 'add-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 1,
                ),
            14 =>
                array(
                    'id' => 16,
                    'name' => 'Edit Metrics',
                    'slug' => 'edit-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 3,
                ),
            15 =>
                array(
                    'id' => 17,
                    'name' => 'Delete Metrics',
                    'slug' => 'delete-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 4,
                ),
            16 =>
                array(
                    'id' => 18,
                    'name' => 'List of Assigned Metrics',
                    'slug' => 'list-of-assigned-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 2,
                ),
            17 =>
                array(
                    'id' => 19,
                    'name' => 'Assign Metrics',
                    'slug' => 'assign-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 1,
                ),
            18 =>
                array(
                    'id' => 20,
                    'name' => 'Edit Assign Metrics',
                    'slug' => 'edit-assign-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 3,
                ),
            19 =>
                array(
                    'id' => 21,
                    'name' => 'Delete Assigned Metrics',
                    'slug' => 'delete-assigned-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 4,
                ),
            20 =>
                array(
                    'id' => 22,
                    'name' => 'List of Metric Categories',
                    'slug' => 'list-of-metric-categories',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 2,
                ),
            21 =>
                array(
                    'id' => 23,
                    'name' => 'Add Metric Category',
                    'slug' => 'add-metric-category',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 1,
                ),
            22 =>
                array(
                    'id' => 24,
                    'name' => 'Edit Metric Category',
                    'slug' => 'edit-metric-category',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 3,
                ),
            23 =>
                array(
                    'id' => 25,
                    'name' => 'Delete Metric Category',
                    'slug' => 'delete-metric-category',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 4,
                ),
            24 =>
                array(
                    'id' => 26,
                    'name' => 'List Designations',
                    'slug' => 'list-designation',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 5,
                    'permission_basic_type_id' => 2,
                ),
            25 =>
                array(
                    'id' => 27,
                    'name' => 'Add Designations',
                    'slug' => 'add-designation',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 5,
                    'permission_basic_type_id' => 1,
                ),
            26 =>
                array(
                    'id' => 28,
                    'name' => 'Edit Designations',
                    'slug' => 'edit-designations',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 5,
                    'permission_basic_type_id' => 3,
                ),
            27 =>
                array(
                    'id' => 29,
                    'name' => 'Delete Designations',
                    'slug' => 'delete-designations',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 5,
                    'permission_basic_type_id' => 4,
                ),
            28 =>
                array(
                    'id' => 30,
                    'name' => 'List of Roles',
                    'slug' => 'list-of-roles',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 6,
                    'permission_basic_type_id' => 2,
                ),
            29 =>
                array(
                    'id' => 31,
                    'name' => 'Assign Roles',
                    'slug' => 'assign-roles',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 6,
                    'permission_basic_type_id' => 1,
                ),
            30 =>
                array(
                    'id' => 32,
                    'name' => 'Edit Roles',
                    'slug' => 'edit-roles',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 6,
                    'permission_basic_type_id' => 3,
                ),
            31 =>
                array(
                    'id' => 33,
                    'name' => 'Delete Roles',
                    'slug' => 'delete-roles',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 6,
                    'permission_basic_type_id' => 4,
                ),
            32 =>
                array(
                    'id' => 34,
                    'name' => 'List of Reports',
                    'slug' => 'list-of-reports',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 8,
                    'permission_basic_type_id' => 2,
                ),
            33 =>
                array(
                    'id' => 35,
                    'name' => 'View Reports',
                    'slug' => 'view-reports',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 8,
                    'permission_basic_type_id' => 1,
                ),
            34 =>
                array(
                    'id' => 36,
                    'name' => 'Edit Reports',
                    'slug' => 'edit-reports',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 8,
                    'permission_basic_type_id' => 3,
                ),
            35 =>
                array(
                    'id' => 37,
                    'name' => 'Show Revisions',
                    'slug' => 'show-revisions',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 7,
                    'permission_basic_type_id' => 2,
                ),
            36 =>
                array(
                    'id' => 38,
                    'name' => 'View Projects',
                    'slug' => 'view-projects',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 1,
                    'permission_basic_type_id' => 2,
                ),
            37 =>
                array(
                    'id' => 39,
                    'name' => 'View Navigators',
                    'slug' => 'view-navigators',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 2,
                    'permission_basic_type_id' => 2,
                ),
            38 =>
                array(
                    'id' => 40,
                    'name' => 'View Users',
                    'slug' => 'view-users',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 3,
                    'permission_basic_type_id' => 2,
                ),
            39 =>
                array(
                    'id' => 41,
                    'name' => 'View Metrics',
                    'slug' => 'view-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 2,
                ),
            40 =>
                array(
                    'id' => 42,
                    'name' => 'View Assign Metrics',
                    'slug' => 'view-assign-metrics',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 2,
                ),
            41 =>
                array(
                    'id' => 43,
                    'name' => 'View Metrics Categories',
                    'slug' => 'view-metrics-categories',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 4,
                    'permission_basic_type_id' => 2,
                ),
            42 =>
                array(
                    'id' => 44,
                    'name' => 'View Designations',
                    'slug' => 'view-designations',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 5,
                    'permission_basic_type_id' => 2,
                ),
            43 =>
                array(
                    'id' => 45,
                    'name' => 'View Roles',
                    'slug' => 'view-roles',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 6,
                    'permission_basic_type_id' => 2,
                ),
            44 =>
                array(
                    'id' => 46,
                    'name' => 'List of Practices',
                    'slug' => 'list-of-practices',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 9,
                    'permission_basic_type_id' => 2,
                ),
            45 =>
                array(
                    'id' => 47,
                    'name' => 'Add Practices',
                    'slug' => 'add-practices',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 9,
                    'permission_basic_type_id' => 1,
                ),
            46 =>
                array(
                    'id' => 48,
                    'name' => 'Edit Practices',
                    'slug' => 'edit-practices',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 9,
                    'permission_basic_type_id' => 3,
                ),
            47 =>
                array(
                    'id' => 49,
                    'name' => 'Delete Practices',
                    'slug' => 'delete-practices',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 9,
                    'permission_basic_type_id' => 4,
                ),
            48 =>
                array(
                    'id' => 50,
                    'name' => 'Feedback form',
                    'slug' => 'feedback-form',
                    'description' => NULL,
                    'model' => NULL,
                    'created_at' => '0000-00-00 00:00:00',
                    'updated_at' => '0000-00-00 00:00:00',
                    'permission_group_id' => 10,
                    'permission_basic_type_id' => 2,
                ),
        ));
    }

}
